{
 "title": "NSO Metrics",
 "description": "Metrics on Cisco NSO",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "jaeger_base_url", "query": "http://127.0.0.1:16686/" }
  ]
 },
 "panels": [
  {
   "title": "transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysadmin_gauge_transaction_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue executing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysadmin_gauge_commit_queue_item_executing",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue length",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysadmin_gauge_commit_queue_item",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Transaction throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: true)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Longest transactions",
   "type": "table",
   "description": "This is a top list of the longest transactions for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"trace_id\" or r._field == \"tid\")\n  |> filter(fn: (r) => r.name == \"applying transaction\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \n  \nunion(tables: [duration, trace_id])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"trace_id\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Transaction lock & queue length",
   "type": "timeseries",
   "description": "The shaded red background shows when the transaction-lock is held (but will tend to overestimate due to time aggregation, zoom in for a better look!). The yellow line is a moving average of the time the transaction-lock is held.\nFinally, the blue line shows the length of the queue to the transaction-lock, i.e. how many transactions are trying to acquire the transaction-lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction-lock\")\n  |> filter(fn: (r) => r._field == \"held\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction-lock\")\n  |> filter(fn: (r) => r._field == \"queue-length\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction-lock\")\n  |> filter(fn: (r) => r._field == \"held\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Transaction duration",
   "type": "timeseries",
   "description": "A histogram of total transaction duration. Notice this includes parts outside of the transaction-lock.\n\nX-axis shows buckets of transaction duration in seconds.\nY-axis is the number of transactions in that bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value/1000.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HA synchronization time",
     "type": "timeseries",
     "description": "Time spent synchronizing changes in a HA group.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"distributing configuration data changeset to all (available) slaves\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
      },
      {
       "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"distributing operational data changeset to all (available) slaves\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waiting for transaction lock",
   "type": "timeseries",
   "description": "The time to grab the transaction lock plotted against the transaction lock queue length.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction-lock\")\n  |> filter(fn: (r) => r._field == \"queue-length\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Longest wait for transaction lock",
   "type": "table",
   "description": "This is a top list of the transactions that had to wait the longest in queue to acquire the transaction lock.\n\nThis list is hardly actionable in the sense that you wouldn't start looking at these transactions for tuning performance. Instead, these transactions are those that have waited the longest for other transactions to finish.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"trace_id\")\n  |> filter(fn: (r) => r.name == \"holding transaction lock\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \nunion(tables: [duration, trace_id,])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"trace_id\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Transaction phases",
   "type": "timeseries",
   "description": "The transaction phases as a percentage of the total transaction time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"validate\" or r._field == \"applying transaction\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"validate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"write-start\" or r._field == \"applying transaction\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"write-start\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"prepare\" or r._field == \"applying transaction\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"prepare\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"commit\" or r._field == \"applying transaction\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"commit\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"applying transaction\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Data validation",
   "type": "heatmap",
   "description": "Shows the time it takes to validate the data as a percentage of the total time the transaction lock is held.\n\nA high percentage could indicate problematic XPath constraints that could be optimized.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"pre validate\" or r._field == \"run validation over the changeset\" or r._field == \"run dependency-triggered validation\" or r._field == \"holding transaction lock\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"pre validate\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"run validation over the changeset\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \ndata_field_3 = data\n  |> filter(fn: (r) => r._field == \"run dependency-triggered validation\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_3\")\n \ndata_field_4 = data\n  |> filter(fn: (r) => r._field == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_4\")\n \nunion(tables: [data_field_1, data_field_2, data_field_3, data_field_4])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: ((r.data_field_1+r.data_field_2+r.data_field_3)/r.data_field_4)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Rollback file creation",
   "type": "heatmap",
   "description": "Shows the time it takes to create the rollback file as a percentage of the total time the transaction lock is held.\n\nIt is possible to disable rollback files for NSO if not needed for the deployment and can yield a non-negligible performance improvement. For very short transactions the rollback file creation can take a unproportionately large percentage and might be somewhat misleading.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"creating rollback file\" or r._field == \"holding transaction lock\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"creating rollback file\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Rollback file creation",
   "type": "timeseries",
   "description": "Time spent creating the rollback file for a transaction \n\nAlso compared ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"creating rollback file\" or r._field == \"holding transaction lock\")\n \ndata_field_1 = data\n  |> filter(fn: (r) => r._field == \"creating rollback file\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_1\")\n \ndata_field_2 = data\n  |> filter(fn: (r) => r._field == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"data_field_2\")\n \nunion(tables: [data_field_1, data_field_2])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with _value: (r.data_field_1/r.data_field_2)*100.0 }))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"holding transaction lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transaction\")\n  |> filter(fn: (r) => r._field == \"creating rollback file\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "service modifications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"create\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"create\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"run service\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"run service\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Mean time in create per service type",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"create\")\n  |> group(columns: [\"service_type\"], mode: \"by\")\n  |> mean()\n  |> keep(columns: [\"_time\", \"_value\", \"service_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Longest service create spans",
   "type": "table",
   "description": "This is a top list of the longest service create spans for the given time period. Use it to identify your slowest services and speed them up!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"service\" or r._field == \"trace_id\")\n  |> filter(fn: (r) => r.name == \"create\" or r._field == \"run service\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \nservice = data\n  |> filter(fn: (r) => r._field == \"service\")\n  |> set(key: \"_field\", value: \"service\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \nunion(tables: [duration, service, trace_id])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"service\", \"trace_id\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Device locks",
   "type": "timeseries",
   "description": "Shows device locks held over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => r.name == \"holding device lock\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Longest get-trans-id",
   "type": "table",
   "description": "This is a top list of the longest get-trans-id operations for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"trace_id\" or r._field == \"tid\")\n  |> filter(fn: (r) => r.name == \"get-trans-id\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \ntid = data\n  |> filter(fn: (r) => r._field == \"tid\")\n  |> set(key: \"_field\", value: \"tid\")\n \nunion(tables: [duration, trace_id, tid])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"trace_id\", \"tid\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Longest device connection",
   "type": "table",
   "description": "This is a top list of the longest get-trans-id operations for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"trace_id\" or r._field == \"tid\")\n  |> filter(fn: (r) => r.name == \"connect\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \ntid = data\n  |> filter(fn: (r) => r._field == \"tid\")\n  |> set(key: \"_field\", value: \"tid\")\n \nunion(tables: [duration, trace_id, tid])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"trace_id\", \"tid\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Longest sync-from",
   "type": "table",
   "description": "This is a top list of the longest sync-from operations for the given time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "query": "data = from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span\")\n  |> filter(fn: (r) => r._field == \"duration\" or r._field == \"trace_id\" or r._field == \"tid\")\n  |> filter(fn: (r) => r.name == \"sync-from\")\n \nduration = data\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> top(n: 100)\n  |> set(key: \"_field\", value: \"duration\")\n \ntrace_id = data\n  |> filter(fn: (r) => r._field == \"trace_id\")\n  |> set(key: \"_field\", value: \"trace_id\")\n \ntid = data\n  |> filter(fn: (r) => r._field == \"tid\")\n  |> set(key: \"_field\", value: \"tid\")\n \nunion(tables: [duration, trace_id, tid])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> keep(columns: [\"_time\", \"duration\", \"trace_id\", \"tid\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Concurrent device operations",
   "type": "timeseries",
   "description": "Shows some device related operations that happen concurrently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"nso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"span-count\")\n  |> filter(fn: (r) => r._field == \"count\")\n  |> filter(fn: (r) => r.name == \"connect\" or r.name == \"pre validate\" or r.name == \"show\" or r.name == \"sync-from\" or r.name == \"taking device lock\" or r.name == \"ned-migrate\")\n  |> group(columns: [\"name\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  }
 ]
}